### ISSUE TITLE
 'WP2StaticNetlify\Controller' not found in /bitnami/word....

### ISSUE THREAD

**Issue by DashBarkHuss** [WP2Static/wp2static-addon-netlify#6]
When I try to activate `wp2static-addon-netlify` I'm getting this error in wordpress:

> Fatal error: Uncaught Error: Class 'WP2StaticNetlify\Controller' not found in /bitnami/wordpress/wp-content/plugins/wp2static-addon-netlify-1.0.1/wp2static-addon-netlify.php:27 Stack trace: #0 /bitnami/wordpress/wp-content/plugins/wp2static-addon-netlify-1.0.1/wp2static-addon-netlify.php(41): run_wp2static_addon_netlify() #1 /opt/bitnami/wordpress/wp-admin/includes/plugin.php(2286): include_once('/bitnami/wordpr...') #2 /opt/bitnami/wordpress/wp-admin/plugins.php(191): plugin_sandbox_scrape() #3 {main} thrown in /bitnami/wordpress/wp-content/plugins/wp2static-addon-netlify-1.0.1/wp2static-addon-netlify.php on line 27

**Comment by leonstafford** [comment]
Hi @DashBarkHuss,

If using from the source code here, you'll need to run `composer install`, to make the required classes available.

Here's a pre-compiled zip installer, which can be easier:

http://wp2staticdlsnov2020.s3.amazonaws.com/wp2static-addon-netlify-1.0.1.zip

Please let me know if either of those helps resolve this

**Comment by DashBarkHuss** [comment]
Thanks Leon for the quick reply. The link to the precompiled one isn't working. That was the same issue I had with this [page](https://wp2static.com/thanks-for-donating) which is why I eventually tried to get the Netlify add on from the github releases section.

All the other links on the **thanks for donating** page work, just not the Netlify one.

**Comment by leonstafford** [comment]
Thanks @DashBarkHuss, not sure what's going on with that particular link for you. I downloaded it again here fine, here it is attached for you:

[wp2static-addon-netlify-1.0.1.zip](https://github.com/leonstafford/wp2static-addon-netlify/files/7132453/wp2static-addon-netlify-1.0.1.zip)

To debug why that other link isn't working, we could maybe try different browsers, or add a cachebusting string at the end, like: https://wp2staticdlsnov2020.s3.amazonaws.com/wp2static-addon-netlify-1.0.1.zip?cachebust=1234

**Comment by DashBarkHuss** [comment]
Thanks the cache busted string worked!
